### ISSUE TITLE
How to set epochs?

### ISSUE THREAD

**Issue by famunir** [pmbaumgartner/setfit#7]
Unable to set the number of epochs in:
```
clf.fit(docs, labels, batch_size=32)
```

Is there a way to set the number of epochs in this method? Also, is there a detailed documentation of all the parameters that can be set to fine tune a model?

Thanks for any help in advance!

**Comment by pmbaumgartner** [comment]
Sorry this isn't better documented. The `train_iter` argument should allow you to set the number of epochs. ref: https://github.com/pmbaumgartner/setfit/blob/main/src/setfit/core.py#L96

**Comment by famunir** [comment]
Thank you @pmbaumgartner
